version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: saarthix-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  app:
    build: .
    container_name: saarthix-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/saarthix
    depends_on:
      - mongo

volumes:
  mongodata:
